[vms]
#vm01 ansible_host=10.100.120.82 ansible_user=root ansible_ssh_pass="ChangeMe_82!"
#vm23 ansible_host=10.101.121.131 ansible_user=root ansible_ssh_pass="ChangeMe_131!"
#vm24 ansible_host=10.101.121.13 ansible_user=root ansible_ssh_pass="ChangeMe_13!"
#vm25 ansible_host=10.101.121.15 ansible_user=root ansible_ssh_pass="ChangeMe_15!"
#vm26 ansible_host=10.101.121.117 ansible_user=root ansible_ssh_pass="ChangeMe_117!"
#vm27 ansible_host=10.101.121.250 ansible_user=root ansible_ssh_pass="ChangeMe_250!"
#vm28 ansible_host=10.101.121.196 ansible_user=root ansible_ssh_pass="ChangeMe_196!"
#vm29 ansible_host=10.101.121.17 ansible_user=root ansible_ssh_pass="ChangeMe_17!"
#vm30 ansible_host=10.101.121.28 ansible_user=root ansible_ssh_pass="ChangeMe_28!"
#vm31 ansible_host=172.27.244.24 ansible_user=root ansible_ssh_pass="ChangeMe_24!"
#vm32 ansible_host=172.27.244.14 ansible_user=root ansible_ssh_pass="ChangeMe_14!"
#vm33 ansible_host=10.101.121.159 ansible_user=root ansible_ssh_pass="ChangeMe_159!"
#vm34 ansible_host=10.101.121.160 ansible_user=root ansible_ssh_pass="ChangeMe_160!"
#vm35 ansible_host=10.101.121.148 ansible_user=root ansible_ssh_pass="ChangeMe_148!"
#vm36 ansible_host=10.101.121.99 ansible_user=root ansible_ssh_pass="ChangeMe_99!"
#vm37 ansible_host=10.101.121.234 ansible_user=root ansible_ssh_pass="ChangeMe_234!"
#vm38 ansible_host=10.101.121.224 ansible_user=root ansible_ssh_pass="ChangeMe_224!"

[vms:vars]
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
